C     The constant tables the rest of the decoder reads, and nothing
C     else.
C
C     H.264 is mostly tables.  They are gathered here, filled once into
C     COMMON by H2INIT, and never written again -- so a routine that
C     gets a scan order wrong is wrong in one place, and a table that is
C     right is right for everybody.  Where a table is generated by a
C     short rule rather than a list of numbers (the two normAdjust
C     matrices, the z-order of the 4x4 blocks) the rule is here rather
C     than its output, because the rule is checkable by eye and 96
C     numbers are not.

      SUBROUTINE H2INIT
      IMPLICIT NONE
      INCLUDE 'h264com.inc'
      INTEGER I, J, K, M, BX, BY, Z, IDX
      INTEGER V4(0:5,0:2), V8(0:5,0:5), D8S(0:15)
      INTEGER RT(0:3,0:63), TL(0:63), TM(0:63)
      INTEGER Z4(0:15), Z8(0:63), S8(0:62), L8(0:62)
      INTEGER CQ(0:51), AL(0:51), BE(0:51), TC(0:51,3)

C     Table 9-44, rangeTabLPS, transposed on the way in so that the hot
C     lookup in H2DEC is RLPS(pStateIdx, qRangeIdx) with the state --
C     the index that changes on every bin -- varying fastest.
      DATA RT /
     +  128,176,208,240, 128,167,197,227, 128,158,187,216,
     +  123,150,178,205, 116,142,169,195, 111,135,160,185,
     +  105,128,152,175, 100,122,144,166,  95,116,137,158,
     +   90,110,130,150,  85,104,123,142,  81, 99,117,135,
     +   77, 94,111,128,  73, 89,105,122,  69, 85,100,116,
     +   66, 80, 95,110,  62, 76, 90,104,  59, 72, 86, 99,
     +   56, 69, 81, 94,  53, 65, 77, 89,  51, 62, 73, 85,
     +   48, 59, 69, 80,  46, 56, 66, 76,  43, 53, 63, 72,
     +   41, 50, 59, 69,  39, 48, 56, 65,  37, 45, 54, 62,
     +   35, 43, 51, 59,  33, 41, 48, 56,  32, 39, 46, 53,
     +   30, 37, 43, 50,  29, 35, 41, 48,  27, 33, 39, 45,
     +   26, 31, 37, 43,  24, 30, 35, 41,  23, 28, 33, 39,
     +   22, 27, 32, 37,  21, 26, 30, 35,  20, 24, 29, 33,
     +   19, 23, 27, 31,  18, 22, 26, 30,  17, 21, 25, 28,
     +   16, 20, 23, 27,  15, 19, 22, 25,  14, 18, 21, 24,
     +   14, 17, 20, 23,  13, 16, 19, 22,  12, 15, 18, 21,
     +   12, 14, 17, 20,  11, 14, 16, 19,  11, 13, 15, 18,
     +   10, 12, 15, 17,  10, 12, 14, 16,   9, 11, 13, 15,
     +    9, 11, 12, 14,   8, 10, 12, 14,   8,  9, 11, 13,
     +    7,  9, 11, 12,   7,  9, 10, 12,   7,  8, 10, 11,
     +    6,  8,  9, 11,   6,  7,  9, 10,   6,  7,  8,  9,
     +    2,  2,  2,  2/

C     Table 9-45, transIdxLPS and transIdxMPS.
      DATA TL /
     +   0, 0, 1, 2, 2, 4, 4, 5, 6, 7, 8, 9, 9,11,11,12,
     +  13,13,15,15,16,16,18,18,19,19,21,21,22,22,23,24,
     +  24,25,26,26,27,27,28,29,29,30,30,30,31,32,32,33,
     +  33,33,34,34,35,35,35,36,36,36,37,37,37,38,38,63/
      DATA TM /
     +   1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15,16,
     +  17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,
     +  33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,
     +  49,50,51,52,53,54,55,56,57,58,59,60,61,62,62,63/

C     Table 8-13 and Table 8-14: the zig-zag scans, written as the
C     raster position each scan position lands on.  Frame macroblocks
C     only -- the field scans belong to interlace, which this decoder
C     refuses.
      DATA Z4 / 0, 1, 4, 8, 5, 2, 3, 6, 9,12,13,10, 7,11,14,15/
      DATA Z8 /
     +   0, 1, 8,16, 9, 2, 3,10, 17,24,32,25,18,11, 4, 5,
     +  12,19,26,33,40,48,41,34, 27,20,13, 6, 7,14,21,28,
     +  35,42,49,56,57,50,43,36, 29,22,15,23,30,37,44,51,
     +  58,59,52,45,38,31,39,46, 53,60,61,54,47,55,62,63/

C     Table 9-43: ctxIdxInc for significant_coeff_flag and for
C     last_significant_coeff_flag inside an 8x8 block.  63 positions
C     share 15 and 9 contexts respectively, which is the whole reason an
C     8x8 block does not need 64 contexts of its own.
      DATA S8 /
     +   0, 1, 2, 3, 4, 5, 5, 4, 4, 3, 3, 4, 4, 4, 5, 5,
     +   4, 4, 4, 4, 3, 3, 6, 7, 7, 7, 8, 9,10, 9, 8, 7,
     +   7, 6,11,12,13,11, 6, 7, 8, 9,14,10, 9, 8, 6,11,
     +  12,13,11, 6, 9,14,10, 9,11,12,13,11,14,10,12/
      DATA L8 /
     +   0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     +   2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
     +   3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4,
     +   5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8/

C     Table 8-15: QPc as a function of qPi.  Below 30 the mapping is the
C     identity, so only the tail is a table; the head is filled by the
C     loop underneath and the two together are indexed without a branch.
      DATA CQ /
     +   0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15,
     +  16,17,18,19,20,21,22,23,24,25,26,27,28,29,
     +  29,30,31,32,32,33,34,34,35,35,36,36,37,37,37,38,
     +  38,38,39,39,39,39/

C     Table 8-16, alpha and beta against indexA and indexB.
      DATA AL /
     +   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     +   4, 4, 5, 6, 7, 8, 9,10,12,13,15,17,20,22,25,28,
     +  32,36,40,45,50,56,63,71,80,90,101,113,127,144,162,
     +  182,203,226,255,255/
      DATA BE /
     +   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     +   2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 6, 6, 7, 7, 8, 8,
     +   9, 9,10,10,11,11,12,12,13,13,14,14,15,15,16,16,
     +  17,17,18,18/

C     Table 8-17, tC0, for bS = 1, 2 and 3.  bS = 4 has no tC0; it takes
C     the other filter entirely.
      DATA (TC(I,1), I = 0, 51) /
     +   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     +   0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
     +   1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 6, 6, 7, 8,
     +   9,10,11,13/
      DATA (TC(I,2), I = 0, 51) /
     +   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     +   0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
     +   2, 2, 2, 3, 3, 3, 4, 4, 5, 5, 6, 7, 8, 8,10,11,
     +  12,13,15,17/
      DATA (TC(I,3), I = 0, 51) /
     +   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     +   0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3,
     +   3, 3, 4, 4, 4, 5, 6, 6, 7, 8, 9,10,11,13,14,16,
     +  18,20,23,25/

C     The three columns of normAdjust4x4 (8-317) and the six of
C     normAdjust8x8 (8-322): which column a position takes is a parity
C     rule, spelled out in the loops below.
      DATA V4 /
     +  10,11,13,14,16,18,
     +  16,18,20,23,25,29,
     +  13,14,16,18,20,23/
      DATA V8 /
     +  20,22,26,28,32,36,
     +  18,19,23,25,28,32,
     +  32,35,42,45,51,58,
     +  19,21,24,26,30,34,
     +  25,28,33,35,40,46,
     +  24,26,31,33,38,43/
C     Which of those six columns each (i mod 4, j mod 4) position takes.
      DATA D8S / 0,3,4,3, 3,1,5,1, 4,5,2,5, 3,1,5,1/

      DO 20 I = 0, 63
         DO 10 J = 0, 3
            RLPS(I,J) = RT(J,I)
   10    CONTINUE
         TLPS(I) = TL(I)
         TMPS(I) = TM(I)
   20 CONTINUE

      DO 30 I = 0, 15
         ZZ4(I) = Z4(I)
   30 CONTINUE
      DO 40 I = 0, 63
         ZZ8(I) = Z8(I)
   40 CONTINUE
      DO 50 I = 0, 62
         SIG8(I) = S8(I)
         LST8(I) = L8(I)
   50 CONTINUE
      DO 60 I = 0, 51
         CHQP(I) = CQ(I)
         ALPHT(I) = AL(I)
         BETAT(I) = BE(I)
         TC0T(I,1) = TC(I,1)
         TC0T(I,2) = TC(I,2)
         TC0T(I,3) = TC(I,3)
   60 CONTINUE

C     The 4x4 luma blocks are numbered in the z-order of 6.4.3, which is
C     two bits of x interleaved with two bits of y.  Both directions of
C     that mapping are wanted often enough to be worth a table each.
      DO 80 BY = 0, 3
         DO 70 BX = 0, 3
            Z = ISHFT(IAND(BY,2),2) + ISHFT(IAND(BX,2),1)
     +          + ISHFT(IAND(BY,1),1) + IAND(BX,1)
            ZORD(BX,BY) = Z
            BLKX(Z) = BX * 4
            BLKY(Z) = BY * 4
   70    CONTINUE
   80 CONTINUE

C     normAdjust4x4(m, i, j): first column when both indices are even,
C     second when both are odd, third otherwise.  Held in raster order
C     so the dequantiser can index it with the same number it indexes
C     the coefficient block with.
      DO 100 M = 0, 5
         DO 90 IDX = 0, 15
            I = IDX / 4
            J = MOD(IDX, 4)
            IF (IAND(I,1) .EQ. 0 .AND. IAND(J,1) .EQ. 0) THEN
               NADJ4(M,IDX) = V4(M,0)
            ELSE IF (IAND(I,1) .EQ. 1 .AND. IAND(J,1) .EQ. 1) THEN
               NADJ4(M,IDX) = V4(M,1)
            ELSE
               NADJ4(M,IDX) = V4(M,2)
            END IF
   90    CONTINUE
  100 CONTINUE

      DO 120 M = 0, 5
         DO 110 IDX = 0, 63
            I = IDX / 8
            J = MOD(IDX, 8)
            K = IAND(I,3) * 4 + IAND(J,3)
            NADJ8(M,IDX) = V8(M, D8S(K))
  110    CONTINUE
  120 CONTINUE

      CALL H2CTAB
      RETURN
      END
